/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationIndexRouteImport } from './routes/formation.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as FormationItemIdRouteImport } from './routes/formation.$itemId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthedWelfareRouteImport } from './routes/_authed.welfare'
import { Route as AuthedUniformsRouteImport } from './routes/_authed.uniforms'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed.notifications'
import { Route as AuthedHomeRouteImport } from './routes/_authed.home'
import { Route as AuthedEnrollRouteImport } from './routes/_authed.enroll'
import { Route as AuthedCusaRouteImport } from './routes/_authed.cusa'
import { Route as AuthedAccountRouteImport } from './routes/_authed.account'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed.profile.index'
import { Route as AuthedMissionIndexRouteImport } from './routes/_authed.mission.index'
import { Route as AuthedProfileEditRouteImport } from './routes/_authed.profile.edit'
import { Route as AuthedMissionHistoryRouteImport } from './routes/_authed.mission.history'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationIndexRoute = FormationIndexRouteImport.update({
  id: '/formation/',
  path: '/formation/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationItemIdRoute = FormationItemIdRouteImport.update({
  id: '/formation/$itemId',
  path: '/formation/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWelfareRoute = AuthedWelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUniformsRoute = AuthedUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHomeRoute = AuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnrollRoute = AuthedEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCusaRoute = AuthedCusaRouteImport.update({
  id: '/cusa',
  path: '/cusa',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMissionIndexRoute = AuthedMissionIndexRouteImport.update({
  id: '/mission/',
  path: '/mission/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileEditRoute = AuthedProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMissionHistoryRoute = AuthedMissionHistoryRouteImport.update({
  id: '/mission/history',
  path: '/mission/history',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthedAccountRoute
  '/cusa': typeof AuthedCusaRoute
  '/enroll': typeof AuthedEnrollRoute
  '/home': typeof AuthedHomeRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/uniforms': typeof AuthedUniformsRoute
  '/welfare': typeof AuthedWelfareRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/formation/$itemId': typeof FormationItemIdRoute
  '/events/': typeof EventsIndexRoute
  '/formation/': typeof FormationIndexRoute
  '/mission/history': typeof AuthedMissionHistoryRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/mission/': typeof AuthedMissionIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account': typeof AuthedAccountRoute
  '/cusa': typeof AuthedCusaRoute
  '/enroll': typeof AuthedEnrollRoute
  '/home': typeof AuthedHomeRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/uniforms': typeof AuthedUniformsRoute
  '/welfare': typeof AuthedWelfareRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/formation/$itemId': typeof FormationItemIdRoute
  '/events': typeof EventsIndexRoute
  '/formation': typeof FormationIndexRoute
  '/mission/history': typeof AuthedMissionHistoryRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/mission': typeof AuthedMissionIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/cusa': typeof AuthedCusaRoute
  '/_authed/enroll': typeof AuthedEnrollRoute
  '/_authed/home': typeof AuthedHomeRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/uniforms': typeof AuthedUniformsRoute
  '/_authed/welfare': typeof AuthedWelfareRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/formation/$itemId': typeof FormationItemIdRoute
  '/events/': typeof EventsIndexRoute
  '/formation/': typeof FormationIndexRoute
  '/_authed/mission/history': typeof AuthedMissionHistoryRoute
  '/_authed/profile/edit': typeof AuthedProfileEditRoute
  '/_authed/mission/': typeof AuthedMissionIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/cusa'
    | '/enroll'
    | '/home'
    | '/notifications'
    | '/uniforms'
    | '/welfare'
    | '/events/$eventId'
    | '/formation/$itemId'
    | '/events/'
    | '/formation/'
    | '/mission/history'
    | '/profile/edit'
    | '/mission/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/account'
    | '/cusa'
    | '/enroll'
    | '/home'
    | '/notifications'
    | '/uniforms'
    | '/welfare'
    | '/events/$eventId'
    | '/formation/$itemId'
    | '/events'
    | '/formation'
    | '/mission/history'
    | '/profile/edit'
    | '/mission'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authed/account'
    | '/_authed/cusa'
    | '/_authed/enroll'
    | '/_authed/home'
    | '/_authed/notifications'
    | '/_authed/uniforms'
    | '/_authed/welfare'
    | '/events/$eventId'
    | '/formation/$itemId'
    | '/events/'
    | '/formation/'
    | '/_authed/mission/history'
    | '/_authed/profile/edit'
    | '/_authed/mission/'
    | '/_authed/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  FormationItemIdRoute: typeof FormationItemIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FormationIndexRoute: typeof FormationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/': {
      id: '/formation/'
      path: '/formation'
      fullPath: '/formation/'
      preLoaderRoute: typeof FormationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/$itemId': {
      id: '/formation/$itemId'
      path: '/formation/$itemId'
      fullPath: '/formation/$itemId'
      preLoaderRoute: typeof FormationItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/welfare': {
      id: '/_authed/welfare'
      path: '/welfare'
      fullPath: '/welfare'
      preLoaderRoute: typeof AuthedWelfareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/uniforms': {
      id: '/_authed/uniforms'
      path: '/uniforms'
      fullPath: '/uniforms'
      preLoaderRoute: typeof AuthedUniformsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/home': {
      id: '/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthedHomeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/enroll': {
      id: '/_authed/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof AuthedEnrollRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cusa': {
      id: '/_authed/cusa'
      path: '/cusa'
      fullPath: '/cusa'
      preLoaderRoute: typeof AuthedCusaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mission/': {
      id: '/_authed/mission/'
      path: '/mission'
      fullPath: '/mission/'
      preLoaderRoute: typeof AuthedMissionIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/edit': {
      id: '/_authed/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthedProfileEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mission/history': {
      id: '/_authed/mission/history'
      path: '/mission/history'
      fullPath: '/mission/history'
      preLoaderRoute: typeof AuthedMissionHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedCusaRoute: typeof AuthedCusaRoute
  AuthedEnrollRoute: typeof AuthedEnrollRoute
  AuthedHomeRoute: typeof AuthedHomeRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedUniformsRoute: typeof AuthedUniformsRoute
  AuthedWelfareRoute: typeof AuthedWelfareRoute
  AuthedMissionHistoryRoute: typeof AuthedMissionHistoryRoute
  AuthedProfileEditRoute: typeof AuthedProfileEditRoute
  AuthedMissionIndexRoute: typeof AuthedMissionIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedCusaRoute: AuthedCusaRoute,
  AuthedEnrollRoute: AuthedEnrollRoute,
  AuthedHomeRoute: AuthedHomeRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedUniformsRoute: AuthedUniformsRoute,
  AuthedWelfareRoute: AuthedWelfareRoute,
  AuthedMissionHistoryRoute: AuthedMissionHistoryRoute,
  AuthedProfileEditRoute: AuthedProfileEditRoute,
  AuthedMissionIndexRoute: AuthedMissionIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  FormationItemIdRoute: FormationItemIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  FormationIndexRoute: FormationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
