/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCusaRouteImport } from './routes/admin.cusa'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEnrollmentRouteImport } from './routes/admin.enrollment'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFinancesRouteImport } from './routes/admin.finances'
import { Route as AdminFormationRouteImport } from './routes/admin.formation'
import { Route as AdminLeadersRouteImport } from './routes/admin.leaders'
import { Route as AdminMissionRouteImport } from './routes/admin.mission'
import { Route as AdminPatronageRouteImport } from './routes/admin.patronage'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUniformsRouteImport } from './routes/admin.uniforms'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWelfareRouteImport } from './routes/admin.welfare'
import { Route as AdminYouthsRouteImport } from './routes/admin.youths'
import { Route as ApiCusaRouteImport } from './routes/api/cusa'
import { Route as ApiEnrollmentsRouteImport } from './routes/api/enrollments'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiLeadersRouteImport } from './routes/api/leaders'
import { Route as ApiWelfareRouteImport } from './routes/api/welfare'
import { Route as ApiYouthsRouteImport } from './routes/api/youths'
import { Route as CheckinEventIdRouteImport } from './routes/checkin.$eventId'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as PortalAuthRouteImport } from './routes/portal.auth'
import { Route as PortalEnrollRouteImport } from './routes/portal.enroll'
import { Route as PortalEventsRouteImport } from './routes/portal.events'
import { Route as PortalFormationRouteImport } from './routes/portal.formation'
import { Route as AdminEventCheckinEventIdRouteImport } from './routes/admin.event-checkin.$eventId'
import { Route as AdminEventEventIdRouteImport } from './routes/admin.event.$eventId'
import { Route as AdminFormationBulletinRouteImport } from './routes/admin.formation.bulletin'
import { Route as AdminFormationYfpRouteImport } from './routes/admin.formation.yfp'
import { Route as ApiAdminInviteUserRouteImport } from './routes/api/admin/invite-user'
import { Route as ApiSheetsErrorsRouteImport } from './routes/api/sheets/errors'
import { Route as ApiSheetsLeadershipRouteImport } from './routes/api/sheets/leadership'
import { Route as ApiUniformsOrdersRouteImport } from './routes/api/uniforms/orders'
import { Route as ApiUniformsSkusRouteImport } from './routes/api/uniforms/skus'
import { Route as PortalEventsEventIdRouteImport } from './routes/portal.events.$eventId'
import { Route as AdminFormationYfpIndexRouteImport } from './routes/admin.formation.yfp.index'
import { Route as AdminFormationYfpAnalyticsRouteImport } from './routes/admin.formation.yfp.analytics'
import { Route as AdminFormationYfpQuestionsRouteImport } from './routes/admin.formation.yfp.questions'
import { Route as AdminFormationYfpPillarsPillarIdSubPillarsRouteImport } from './routes/admin.formation.yfp.pillars.$pillarId.sub-pillars'
import { Route as AdminFormationYfpSubPillarsSubPillarIdArticlesRouteImport } from './routes/admin.formation.yfp.sub-pillars.$subPillarId.articles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCusaRoute = AdminCusaRouteImport.update({
  id: '/cusa',
  path: '/cusa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentRoute = AdminEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormationRoute = AdminFormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadersRoute = AdminLeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionRoute = AdminMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatronageRoute = AdminPatronageRouteImport.update({
  id: '/patronage',
  path: '/patronage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUniformsRoute = AdminUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWelfareRoute = AdminWelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYouthsRoute = AdminYouthsRouteImport.update({
  id: '/youths',
  path: '/youths',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCusaRoute = ApiCusaRouteImport.update({
  id: '/api/cusa',
  path: '/api/cusa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollmentsRoute = ApiEnrollmentsRouteImport.update({
  id: '/api/enrollments',
  path: '/api/enrollments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadersRoute = ApiLeadersRouteImport.update({
  id: '/api/leaders',
  path: '/api/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWelfareRoute = ApiWelfareRouteImport.update({
  id: '/api/welfare',
  path: '/api/welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYouthsRoute = ApiYouthsRouteImport.update({
  id: '/api/youths',
  path: '/api/youths',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinEventIdRoute = CheckinEventIdRouteImport.update({
  id: '/checkin/$eventId',
  path: '/checkin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEnrollRoute = PortalEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFormationRoute = PortalFormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => PortalRoute,
} as any)
const AdminEventCheckinEventIdRoute =
  AdminEventCheckinEventIdRouteImport.update({
    id: '/event-checkin/$eventId',
    path: '/event-checkin/$eventId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEventEventIdRoute = AdminEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormationBulletinRoute = AdminFormationBulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => AdminFormationRoute,
} as any)
const AdminFormationYfpRoute = AdminFormationYfpRouteImport.update({
  id: '/yfp',
  path: '/yfp',
  getParentRoute: () => AdminFormationRoute,
} as any)
const ApiAdminInviteUserRoute = ApiAdminInviteUserRouteImport.update({
  id: '/api/admin/invite-user',
  path: '/api/admin/invite-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSheetsErrorsRoute = ApiSheetsErrorsRouteImport.update({
  id: '/api/sheets/errors',
  path: '/api/sheets/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSheetsLeadershipRoute = ApiSheetsLeadershipRouteImport.update({
  id: '/api/sheets/leadership',
  path: '/api/sheets/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUniformsOrdersRoute = ApiUniformsOrdersRouteImport.update({
  id: '/api/uniforms/orders',
  path: '/api/uniforms/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUniformsSkusRoute = ApiUniformsSkusRouteImport.update({
  id: '/api/uniforms/skus',
  path: '/api/uniforms/skus',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventsEventIdRoute = PortalEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => PortalEventsRoute,
} as any)
const AdminFormationYfpIndexRoute = AdminFormationYfpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFormationYfpRoute,
} as any)
const AdminFormationYfpAnalyticsRoute =
  AdminFormationYfpAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminFormationYfpRoute,
  } as any)
const AdminFormationYfpQuestionsRoute =
  AdminFormationYfpQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AdminFormationYfpRoute,
  } as any)
const AdminFormationYfpPillarsPillarIdSubPillarsRoute =
  AdminFormationYfpPillarsPillarIdSubPillarsRouteImport.update({
    id: '/pillars/$pillarId/sub-pillars',
    path: '/pillars/$pillarId/sub-pillars',
    getParentRoute: () => AdminFormationYfpRoute,
  } as any)
const AdminFormationYfpSubPillarsSubPillarIdArticlesRoute =
  AdminFormationYfpSubPillarsSubPillarIdArticlesRouteImport.update({
    id: '/sub-pillars/$subPillarId/articles',
    path: '/sub-pillars/$subPillarId/articles',
    getParentRoute: () => AdminFormationYfpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/formation': typeof AdminFormationRouteWithChildren
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/patronage': typeof AdminPatronageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/api/cusa': typeof ApiCusaRoute
  '/api/enrollments': typeof ApiEnrollmentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/leaders': typeof ApiLeadersRoute
  '/api/welfare': typeof ApiWelfareRoute
  '/api/youths': typeof ApiYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/enroll': typeof PortalEnrollRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/formation': typeof PortalFormationRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/event-checkin/$eventId': typeof AdminEventCheckinEventIdRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
  '/admin/formation/bulletin': typeof AdminFormationBulletinRoute
  '/admin/formation/yfp': typeof AdminFormationYfpRouteWithChildren
  '/api/admin/invite-user': typeof ApiAdminInviteUserRoute
  '/api/sheets/errors': typeof ApiSheetsErrorsRoute
  '/api/sheets/leadership': typeof ApiSheetsLeadershipRoute
  '/api/uniforms/orders': typeof ApiUniformsOrdersRoute
  '/api/uniforms/skus': typeof ApiUniformsSkusRoute
  '/portal/events/$eventId': typeof PortalEventsEventIdRoute
  '/admin/formation/yfp/analytics': typeof AdminFormationYfpAnalyticsRoute
  '/admin/formation/yfp/questions': typeof AdminFormationYfpQuestionsRoute
  '/admin/formation/yfp/': typeof AdminFormationYfpIndexRoute
  '/admin/formation/yfp/pillars/$pillarId/sub-pillars': typeof AdminFormationYfpPillarsPillarIdSubPillarsRoute
  '/admin/formation/yfp/sub-pillars/$subPillarId/articles': typeof AdminFormationYfpSubPillarsSubPillarIdArticlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/formation': typeof AdminFormationRouteWithChildren
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/patronage': typeof AdminPatronageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/api/cusa': typeof ApiCusaRoute
  '/api/enrollments': typeof ApiEnrollmentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/leaders': typeof ApiLeadersRoute
  '/api/welfare': typeof ApiWelfareRoute
  '/api/youths': typeof ApiYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/enroll': typeof PortalEnrollRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/formation': typeof PortalFormationRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/event-checkin/$eventId': typeof AdminEventCheckinEventIdRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
  '/admin/formation/bulletin': typeof AdminFormationBulletinRoute
  '/api/admin/invite-user': typeof ApiAdminInviteUserRoute
  '/api/sheets/errors': typeof ApiSheetsErrorsRoute
  '/api/sheets/leadership': typeof ApiSheetsLeadershipRoute
  '/api/uniforms/orders': typeof ApiUniformsOrdersRoute
  '/api/uniforms/skus': typeof ApiUniformsSkusRoute
  '/portal/events/$eventId': typeof PortalEventsEventIdRoute
  '/admin/formation/yfp/analytics': typeof AdminFormationYfpAnalyticsRoute
  '/admin/formation/yfp/questions': typeof AdminFormationYfpQuestionsRoute
  '/admin/formation/yfp': typeof AdminFormationYfpIndexRoute
  '/admin/formation/yfp/pillars/$pillarId/sub-pillars': typeof AdminFormationYfpPillarsPillarIdSubPillarsRoute
  '/admin/formation/yfp/sub-pillars/$subPillarId/articles': typeof AdminFormationYfpSubPillarsSubPillarIdArticlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/formation': typeof AdminFormationRouteWithChildren
  '/admin/leaders': typeof AdminLeadersRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/patronage': typeof AdminPatronageRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/api/cusa': typeof ApiCusaRoute
  '/api/enrollments': typeof ApiEnrollmentsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/leaders': typeof ApiLeadersRoute
  '/api/welfare': typeof ApiWelfareRoute
  '/api/youths': typeof ApiYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/auth': typeof PortalAuthRoute
  '/portal/enroll': typeof PortalEnrollRoute
  '/portal/events': typeof PortalEventsRouteWithChildren
  '/portal/formation': typeof PortalFormationRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/event-checkin/$eventId': typeof AdminEventCheckinEventIdRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
  '/admin/formation/bulletin': typeof AdminFormationBulletinRoute
  '/admin/formation/yfp': typeof AdminFormationYfpRouteWithChildren
  '/api/admin/invite-user': typeof ApiAdminInviteUserRoute
  '/api/sheets/errors': typeof ApiSheetsErrorsRoute
  '/api/sheets/leadership': typeof ApiSheetsLeadershipRoute
  '/api/uniforms/orders': typeof ApiUniformsOrdersRoute
  '/api/uniforms/skus': typeof ApiUniformsSkusRoute
  '/portal/events/$eventId': typeof PortalEventsEventIdRoute
  '/admin/formation/yfp/analytics': typeof AdminFormationYfpAnalyticsRoute
  '/admin/formation/yfp/questions': typeof AdminFormationYfpQuestionsRoute
  '/admin/formation/yfp/': typeof AdminFormationYfpIndexRoute
  '/admin/formation/yfp/pillars/$pillarId/sub-pillars': typeof AdminFormationYfpPillarsPillarIdSubPillarsRoute
  '/admin/formation/yfp/sub-pillars/$subPillarId/articles': typeof AdminFormationYfpSubPillarsSubPillarIdArticlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/portal'
    | '/set-password'
    | '/admin/audit'
    | '/admin/cusa'
    | '/admin/dashboard'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/finances'
    | '/admin/formation'
    | '/admin/leaders'
    | '/admin/mission'
    | '/admin/patronage'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/api/cusa'
    | '/api/enrollments'
    | '/api/events'
    | '/api/leaders'
    | '/api/welfare'
    | '/api/youths'
    | '/checkin/$eventId'
    | '/portal/account'
    | '/portal/auth'
    | '/portal/enroll'
    | '/portal/events'
    | '/portal/formation'
    | '/admin/'
    | '/portal/'
    | '/admin/event-checkin/$eventId'
    | '/admin/event/$eventId'
    | '/admin/formation/bulletin'
    | '/admin/formation/yfp'
    | '/api/admin/invite-user'
    | '/api/sheets/errors'
    | '/api/sheets/leadership'
    | '/api/uniforms/orders'
    | '/api/uniforms/skus'
    | '/portal/events/$eventId'
    | '/admin/formation/yfp/analytics'
    | '/admin/formation/yfp/questions'
    | '/admin/formation/yfp/'
    | '/admin/formation/yfp/pillars/$pillarId/sub-pillars'
    | '/admin/formation/yfp/sub-pillars/$subPillarId/articles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin/audit'
    | '/admin/cusa'
    | '/admin/dashboard'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/finances'
    | '/admin/formation'
    | '/admin/leaders'
    | '/admin/mission'
    | '/admin/patronage'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/api/cusa'
    | '/api/enrollments'
    | '/api/events'
    | '/api/leaders'
    | '/api/welfare'
    | '/api/youths'
    | '/checkin/$eventId'
    | '/portal/account'
    | '/portal/auth'
    | '/portal/enroll'
    | '/portal/events'
    | '/portal/formation'
    | '/admin'
    | '/portal'
    | '/admin/event-checkin/$eventId'
    | '/admin/event/$eventId'
    | '/admin/formation/bulletin'
    | '/api/admin/invite-user'
    | '/api/sheets/errors'
    | '/api/sheets/leadership'
    | '/api/uniforms/orders'
    | '/api/uniforms/skus'
    | '/portal/events/$eventId'
    | '/admin/formation/yfp/analytics'
    | '/admin/formation/yfp/questions'
    | '/admin/formation/yfp'
    | '/admin/formation/yfp/pillars/$pillarId/sub-pillars'
    | '/admin/formation/yfp/sub-pillars/$subPillarId/articles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/portal'
    | '/set-password'
    | '/admin/audit'
    | '/admin/cusa'
    | '/admin/dashboard'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/finances'
    | '/admin/formation'
    | '/admin/leaders'
    | '/admin/mission'
    | '/admin/patronage'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/api/cusa'
    | '/api/enrollments'
    | '/api/events'
    | '/api/leaders'
    | '/api/welfare'
    | '/api/youths'
    | '/checkin/$eventId'
    | '/portal/account'
    | '/portal/auth'
    | '/portal/enroll'
    | '/portal/events'
    | '/portal/formation'
    | '/admin/'
    | '/portal/'
    | '/admin/event-checkin/$eventId'
    | '/admin/event/$eventId'
    | '/admin/formation/bulletin'
    | '/admin/formation/yfp'
    | '/api/admin/invite-user'
    | '/api/sheets/errors'
    | '/api/sheets/leadership'
    | '/api/uniforms/orders'
    | '/api/uniforms/skus'
    | '/portal/events/$eventId'
    | '/admin/formation/yfp/analytics'
    | '/admin/formation/yfp/questions'
    | '/admin/formation/yfp/'
    | '/admin/formation/yfp/pillars/$pillarId/sub-pillars'
    | '/admin/formation/yfp/sub-pillars/$subPillarId/articles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SetPasswordRoute: typeof SetPasswordRoute
  ApiCusaRoute: typeof ApiCusaRoute
  ApiEnrollmentsRoute: typeof ApiEnrollmentsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiLeadersRoute: typeof ApiLeadersRoute
  ApiWelfareRoute: typeof ApiWelfareRoute
  ApiYouthsRoute: typeof ApiYouthsRoute
  CheckinEventIdRoute: typeof CheckinEventIdRoute
  ApiAdminInviteUserRoute: typeof ApiAdminInviteUserRoute
  ApiSheetsErrorsRoute: typeof ApiSheetsErrorsRoute
  ApiSheetsLeadershipRoute: typeof ApiSheetsLeadershipRoute
  ApiUniformsOrdersRoute: typeof ApiUniformsOrdersRoute
  ApiUniformsSkusRoute: typeof ApiUniformsSkusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cusa': {
      id: '/admin/cusa'
      path: '/cusa'
      fullPath: '/admin/cusa'
      preLoaderRoute: typeof AdminCusaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollment': {
      id: '/admin/enrollment'
      path: '/enrollment'
      fullPath: '/admin/enrollment'
      preLoaderRoute: typeof AdminEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formation': {
      id: '/admin/formation'
      path: '/formation'
      fullPath: '/admin/formation'
      preLoaderRoute: typeof AdminFormationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaders': {
      id: '/admin/leaders'
      path: '/leaders'
      fullPath: '/admin/leaders'
      preLoaderRoute: typeof AdminLeadersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mission': {
      id: '/admin/mission'
      path: '/mission'
      fullPath: '/admin/mission'
      preLoaderRoute: typeof AdminMissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patronage': {
      id: '/admin/patronage'
      path: '/patronage'
      fullPath: '/admin/patronage'
      preLoaderRoute: typeof AdminPatronageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uniforms': {
      id: '/admin/uniforms'
      path: '/uniforms'
      fullPath: '/admin/uniforms'
      preLoaderRoute: typeof AdminUniformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/welfare': {
      id: '/admin/welfare'
      path: '/welfare'
      fullPath: '/admin/welfare'
      preLoaderRoute: typeof AdminWelfareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/youths': {
      id: '/admin/youths'
      path: '/youths'
      fullPath: '/admin/youths'
      preLoaderRoute: typeof AdminYouthsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/cusa': {
      id: '/api/cusa'
      path: '/api/cusa'
      fullPath: '/api/cusa'
      preLoaderRoute: typeof ApiCusaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrollments': {
      id: '/api/enrollments'
      path: '/api/enrollments'
      fullPath: '/api/enrollments'
      preLoaderRoute: typeof ApiEnrollmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaders': {
      id: '/api/leaders'
      path: '/api/leaders'
      fullPath: '/api/leaders'
      preLoaderRoute: typeof ApiLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/welfare': {
      id: '/api/welfare'
      path: '/api/welfare'
      fullPath: '/api/welfare'
      preLoaderRoute: typeof ApiWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youths': {
      id: '/api/youths'
      path: '/api/youths'
      fullPath: '/api/youths'
      preLoaderRoute: typeof ApiYouthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$eventId': {
      id: '/checkin/$eventId'
      path: '/checkin/$eventId'
      fullPath: '/checkin/$eventId'
      preLoaderRoute: typeof CheckinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/auth': {
      id: '/portal/auth'
      path: '/auth'
      fullPath: '/portal/auth'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/enroll': {
      id: '/portal/enroll'
      path: '/enroll'
      fullPath: '/portal/enroll'
      preLoaderRoute: typeof PortalEnrollRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events': {
      id: '/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/formation': {
      id: '/portal/formation'
      path: '/formation'
      fullPath: '/portal/formation'
      preLoaderRoute: typeof PortalFormationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/event-checkin/$eventId': {
      id: '/admin/event-checkin/$eventId'
      path: '/event-checkin/$eventId'
      fullPath: '/admin/event-checkin/$eventId'
      preLoaderRoute: typeof AdminEventCheckinEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event/$eventId': {
      id: '/admin/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/admin/event/$eventId'
      preLoaderRoute: typeof AdminEventEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formation/bulletin': {
      id: '/admin/formation/bulletin'
      path: '/bulletin'
      fullPath: '/admin/formation/bulletin'
      preLoaderRoute: typeof AdminFormationBulletinRouteImport
      parentRoute: typeof AdminFormationRoute
    }
    '/admin/formation/yfp': {
      id: '/admin/formation/yfp'
      path: '/yfp'
      fullPath: '/admin/formation/yfp'
      preLoaderRoute: typeof AdminFormationYfpRouteImport
      parentRoute: typeof AdminFormationRoute
    }
    '/api/admin/invite-user': {
      id: '/api/admin/invite-user'
      path: '/api/admin/invite-user'
      fullPath: '/api/admin/invite-user'
      preLoaderRoute: typeof ApiAdminInviteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sheets/errors': {
      id: '/api/sheets/errors'
      path: '/api/sheets/errors'
      fullPath: '/api/sheets/errors'
      preLoaderRoute: typeof ApiSheetsErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sheets/leadership': {
      id: '/api/sheets/leadership'
      path: '/api/sheets/leadership'
      fullPath: '/api/sheets/leadership'
      preLoaderRoute: typeof ApiSheetsLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uniforms/orders': {
      id: '/api/uniforms/orders'
      path: '/api/uniforms/orders'
      fullPath: '/api/uniforms/orders'
      preLoaderRoute: typeof ApiUniformsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uniforms/skus': {
      id: '/api/uniforms/skus'
      path: '/api/uniforms/skus'
      fullPath: '/api/uniforms/skus'
      preLoaderRoute: typeof ApiUniformsSkusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/events/$eventId': {
      id: '/portal/events/$eventId'
      path: '/$eventId'
      fullPath: '/portal/events/$eventId'
      preLoaderRoute: typeof PortalEventsEventIdRouteImport
      parentRoute: typeof PortalEventsRoute
    }
    '/admin/formation/yfp/': {
      id: '/admin/formation/yfp/'
      path: '/'
      fullPath: '/admin/formation/yfp/'
      preLoaderRoute: typeof AdminFormationYfpIndexRouteImport
      parentRoute: typeof AdminFormationYfpRoute
    }
    '/admin/formation/yfp/analytics': {
      id: '/admin/formation/yfp/analytics'
      path: '/analytics'
      fullPath: '/admin/formation/yfp/analytics'
      preLoaderRoute: typeof AdminFormationYfpAnalyticsRouteImport
      parentRoute: typeof AdminFormationYfpRoute
    }
    '/admin/formation/yfp/questions': {
      id: '/admin/formation/yfp/questions'
      path: '/questions'
      fullPath: '/admin/formation/yfp/questions'
      preLoaderRoute: typeof AdminFormationYfpQuestionsRouteImport
      parentRoute: typeof AdminFormationYfpRoute
    }
    '/admin/formation/yfp/pillars/$pillarId/sub-pillars': {
      id: '/admin/formation/yfp/pillars/$pillarId/sub-pillars'
      path: '/pillars/$pillarId/sub-pillars'
      fullPath: '/admin/formation/yfp/pillars/$pillarId/sub-pillars'
      preLoaderRoute: typeof AdminFormationYfpPillarsPillarIdSubPillarsRouteImport
      parentRoute: typeof AdminFormationYfpRoute
    }
    '/admin/formation/yfp/sub-pillars/$subPillarId/articles': {
      id: '/admin/formation/yfp/sub-pillars/$subPillarId/articles'
      path: '/sub-pillars/$subPillarId/articles'
      fullPath: '/admin/formation/yfp/sub-pillars/$subPillarId/articles'
      preLoaderRoute: typeof AdminFormationYfpSubPillarsSubPillarIdArticlesRouteImport
      parentRoute: typeof AdminFormationYfpRoute
    }
  }
}

interface AdminFormationYfpRouteChildren {
  AdminFormationYfpAnalyticsRoute: typeof AdminFormationYfpAnalyticsRoute
  AdminFormationYfpQuestionsRoute: typeof AdminFormationYfpQuestionsRoute
  AdminFormationYfpIndexRoute: typeof AdminFormationYfpIndexRoute
  AdminFormationYfpPillarsPillarIdSubPillarsRoute: typeof AdminFormationYfpPillarsPillarIdSubPillarsRoute
  AdminFormationYfpSubPillarsSubPillarIdArticlesRoute: typeof AdminFormationYfpSubPillarsSubPillarIdArticlesRoute
}

const AdminFormationYfpRouteChildren: AdminFormationYfpRouteChildren = {
  AdminFormationYfpAnalyticsRoute: AdminFormationYfpAnalyticsRoute,
  AdminFormationYfpQuestionsRoute: AdminFormationYfpQuestionsRoute,
  AdminFormationYfpIndexRoute: AdminFormationYfpIndexRoute,
  AdminFormationYfpPillarsPillarIdSubPillarsRoute:
    AdminFormationYfpPillarsPillarIdSubPillarsRoute,
  AdminFormationYfpSubPillarsSubPillarIdArticlesRoute:
    AdminFormationYfpSubPillarsSubPillarIdArticlesRoute,
}

const AdminFormationYfpRouteWithChildren =
  AdminFormationYfpRoute._addFileChildren(AdminFormationYfpRouteChildren)

interface AdminFormationRouteChildren {
  AdminFormationBulletinRoute: typeof AdminFormationBulletinRoute
  AdminFormationYfpRoute: typeof AdminFormationYfpRouteWithChildren
}

const AdminFormationRouteChildren: AdminFormationRouteChildren = {
  AdminFormationBulletinRoute: AdminFormationBulletinRoute,
  AdminFormationYfpRoute: AdminFormationYfpRouteWithChildren,
}

const AdminFormationRouteWithChildren = AdminFormationRoute._addFileChildren(
  AdminFormationRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCusaRoute: typeof AdminCusaRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentRoute: typeof AdminEnrollmentRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminFormationRoute: typeof AdminFormationRouteWithChildren
  AdminLeadersRoute: typeof AdminLeadersRoute
  AdminMissionRoute: typeof AdminMissionRoute
  AdminPatronageRoute: typeof AdminPatronageRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUniformsRoute: typeof AdminUniformsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWelfareRoute: typeof AdminWelfareRoute
  AdminYouthsRoute: typeof AdminYouthsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventCheckinEventIdRoute: typeof AdminEventCheckinEventIdRoute
  AdminEventEventIdRoute: typeof AdminEventEventIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCusaRoute: AdminCusaRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentRoute: AdminEnrollmentRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFinancesRoute: AdminFinancesRoute,
  AdminFormationRoute: AdminFormationRouteWithChildren,
  AdminLeadersRoute: AdminLeadersRoute,
  AdminMissionRoute: AdminMissionRoute,
  AdminPatronageRoute: AdminPatronageRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUniformsRoute: AdminUniformsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWelfareRoute: AdminWelfareRoute,
  AdminYouthsRoute: AdminYouthsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventCheckinEventIdRoute: AdminEventCheckinEventIdRoute,
  AdminEventEventIdRoute: AdminEventEventIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalEventsRouteChildren {
  PortalEventsEventIdRoute: typeof PortalEventsEventIdRoute
}

const PortalEventsRouteChildren: PortalEventsRouteChildren = {
  PortalEventsEventIdRoute: PortalEventsEventIdRoute,
}

const PortalEventsRouteWithChildren = PortalEventsRoute._addFileChildren(
  PortalEventsRouteChildren,
)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalAuthRoute: typeof PortalAuthRoute
  PortalEnrollRoute: typeof PortalEnrollRoute
  PortalEventsRoute: typeof PortalEventsRouteWithChildren
  PortalFormationRoute: typeof PortalFormationRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalAuthRoute: PortalAuthRoute,
  PortalEnrollRoute: PortalEnrollRoute,
  PortalEventsRoute: PortalEventsRouteWithChildren,
  PortalFormationRoute: PortalFormationRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SetPasswordRoute: SetPasswordRoute,
  ApiCusaRoute: ApiCusaRoute,
  ApiEnrollmentsRoute: ApiEnrollmentsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiLeadersRoute: ApiLeadersRoute,
  ApiWelfareRoute: ApiWelfareRoute,
  ApiYouthsRoute: ApiYouthsRoute,
  CheckinEventIdRoute: CheckinEventIdRoute,
  ApiAdminInviteUserRoute: ApiAdminInviteUserRoute,
  ApiSheetsErrorsRoute: ApiSheetsErrorsRoute,
  ApiSheetsLeadershipRoute: ApiSheetsLeadershipRoute,
  ApiUniformsOrdersRoute: ApiUniformsOrdersRoute,
  ApiUniformsSkusRoute: ApiUniformsSkusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
