/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalAuthRouteImport } from './routes/portal.auth'
import { Route as CheckinEventIdRouteImport } from './routes/checkin.$eventId'
import { Route as AdminYouthsRouteImport } from './routes/admin.youths'
import { Route as AdminWelfareRouteImport } from './routes/admin.welfare'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUniformsRouteImport } from './routes/admin.uniforms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMissionRouteImport } from './routes/admin.mission'
import { Route as AdminFormationRouteImport } from './routes/admin.formation'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEnrollmentRouteImport } from './routes/admin.enrollment'
import { Route as AdminCusaRouteImport } from './routes/admin.cusa'
import { Route as AdminEventEventIdRouteImport } from './routes/admin.event.$eventId'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortalRoute,
} as any)
const CheckinEventIdRoute = CheckinEventIdRouteImport.update({
  id: '/checkin/$eventId',
  path: '/checkin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYouthsRoute = AdminYouthsRouteImport.update({
  id: '/youths',
  path: '/youths',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWelfareRoute = AdminWelfareRouteImport.update({
  id: '/welfare',
  path: '/welfare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUniformsRoute = AdminUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionRoute = AdminMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormationRoute = AdminFormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentRoute = AdminEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCusaRoute = AdminCusaRouteImport.update({
  id: '/cusa',
  path: '/cusa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventEventIdRoute = AdminEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/formation': typeof AdminFormationRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/auth': typeof PortalAuthRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/formation': typeof AdminFormationRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/auth': typeof PortalAuthRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/cusa': typeof AdminCusaRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/formation': typeof AdminFormationRoute
  '/admin/mission': typeof AdminMissionRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/uniforms': typeof AdminUniformsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/welfare': typeof AdminWelfareRoute
  '/admin/youths': typeof AdminYouthsRoute
  '/checkin/$eventId': typeof CheckinEventIdRoute
  '/portal/auth': typeof PortalAuthRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/event/$eventId': typeof AdminEventEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/portal'
    | '/admin/cusa'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/formation'
    | '/admin/mission'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/checkin/$eventId'
    | '/portal/auth'
    | '/admin/'
    | '/portal/'
    | '/admin/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/cusa'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/formation'
    | '/admin/mission'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/checkin/$eventId'
    | '/portal/auth'
    | '/admin'
    | '/portal'
    | '/admin/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/portal'
    | '/admin/cusa'
    | '/admin/enrollment'
    | '/admin/events'
    | '/admin/formation'
    | '/admin/mission'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/uniforms'
    | '/admin/users'
    | '/admin/welfare'
    | '/admin/youths'
    | '/checkin/$eventId'
    | '/portal/auth'
    | '/admin/'
    | '/portal/'
    | '/admin/event/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  CheckinEventIdRoute: typeof CheckinEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/auth': {
      id: '/portal/auth'
      path: '/auth'
      fullPath: '/portal/auth'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/checkin/$eventId': {
      id: '/checkin/$eventId'
      path: '/checkin/$eventId'
      fullPath: '/checkin/$eventId'
      preLoaderRoute: typeof CheckinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/youths': {
      id: '/admin/youths'
      path: '/youths'
      fullPath: '/admin/youths'
      preLoaderRoute: typeof AdminYouthsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/welfare': {
      id: '/admin/welfare'
      path: '/welfare'
      fullPath: '/admin/welfare'
      preLoaderRoute: typeof AdminWelfareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uniforms': {
      id: '/admin/uniforms'
      path: '/uniforms'
      fullPath: '/admin/uniforms'
      preLoaderRoute: typeof AdminUniformsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mission': {
      id: '/admin/mission'
      path: '/mission'
      fullPath: '/admin/mission'
      preLoaderRoute: typeof AdminMissionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formation': {
      id: '/admin/formation'
      path: '/formation'
      fullPath: '/admin/formation'
      preLoaderRoute: typeof AdminFormationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollment': {
      id: '/admin/enrollment'
      path: '/enrollment'
      fullPath: '/admin/enrollment'
      preLoaderRoute: typeof AdminEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cusa': {
      id: '/admin/cusa'
      path: '/cusa'
      fullPath: '/admin/cusa'
      preLoaderRoute: typeof AdminCusaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/event/$eventId': {
      id: '/admin/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/admin/event/$eventId'
      preLoaderRoute: typeof AdminEventEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCusaRoute: typeof AdminCusaRoute
  AdminEnrollmentRoute: typeof AdminEnrollmentRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFormationRoute: typeof AdminFormationRoute
  AdminMissionRoute: typeof AdminMissionRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUniformsRoute: typeof AdminUniformsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWelfareRoute: typeof AdminWelfareRoute
  AdminYouthsRoute: typeof AdminYouthsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventEventIdRoute: typeof AdminEventEventIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCusaRoute: AdminCusaRoute,
  AdminEnrollmentRoute: AdminEnrollmentRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFormationRoute: AdminFormationRoute,
  AdminMissionRoute: AdminMissionRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUniformsRoute: AdminUniformsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWelfareRoute: AdminWelfareRoute,
  AdminYouthsRoute: AdminYouthsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventEventIdRoute: AdminEventEventIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAuthRoute: typeof PortalAuthRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAuthRoute: PortalAuthRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  CheckinEventIdRoute: CheckinEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
